name: "Semantic Release Yarn"

description: "Run semantic release for yarn projects"

inputs:
  github-token:
    description: "Github token"
    required: true
  npm-token:
    description: "NPM token"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        cache: yarn
    - run: yarn set version berry
      shell: bash
    - run: yarn
      shell: bash
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
