name: "Semantic Release Yarn"

description: "Run semantic release for yarn projects"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        cache: yarn
    - run: yarn set version berry
      shell: bash
    - run: yarn
      shell: bash
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
