name: "Docker Build"

description: "Build docker image"

inputs:
  context:
    description: "Docker build context"
    required: true
  image:
    description: "Image name"
    required: true
  build-args:
    description: "Docker build args"
  file:
    description: "Dockerfile location"
  prefix:
    description: "Docker tag prefix"
  suffix:
    description: "Docker tag suffix"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ inputs.image }}
        flavor: |
          latest=auto
          prefix=${{ inputs.prefix }}
          suffix=${{ inputs.suffix }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - uses: docker/build-push-action@v5
      with:
        build-args: ${{ inputs.build-args }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
