name: "Semantic Release"

description: "Create a release based on conventional commits"

inputs:
  github-token:
    description: "GitHub token"
    required: false
  npm-token:
    description: "NPM token"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check node version
      id: node-version
      run: echo "version=$(node -v)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/setup-node@v4
      if: ${{ startsWith(steps.node-version.outputs.version, 'v20') != true }}
      with:
        node-version: 20
    - name: Release
      run: |
        npm i -g semantic-release @tiwariav/semantic-release-config@1.3.6
        echo "Using @tiwariav/semantic-release-config $(npm view @tiwariav/semantic-release-config version)"
        semantic-release --extends @tiwariav/semantic-release-config
      shell: bash
      env:
        HUSKY: 0
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
