name: "Semantic Release"

description: "Create a release based on conventional commits"

inputs:
  github-token:
    description: "GitHub token"
    required: false
  npm-token:
    description: "NPM token"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Release
      run: |
        npm i -g semantic-release @tiwariav/semantic-release-config
        semantic-release --extends @tiwariav/semantic-release-config
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
