name: "Semantic Release Yarn"

description: "Create a release based on conventional commits"

inputs:
  create-release:
    description: "Create a release"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Prepare
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        npm i -g commit-and-tag-version @tiwariav/conventional-changelog-preset conventional-changelog-angular
      shell: bash
    - name: Commit and Tag
      run: |
        git fetch --depth=50 --tags --quiet
        commit-and-tag-version --preset @tiwariav/preset
        git push --follow-tags origin main
      shell: bash
    - name: Github Release
      if: ${{ inputs.create-release == 'true' }}
      run: ${{ github.action_path }}/conventional-release/github-release.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
