name: "Setup Yarn Berry"

description: "Setup yarn berry on node"

inputs:
  lint-cache-key:
    description: "Key for lint-cache (disabled if false)"
    required: false
    default: ${{ hashFiles('yarn.lock', 'package.json') }}

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Setup Yarn Berry
      run: |
        corepack enable
        yarn set version berry
        yarn install
        echo ${{ inputs.lint-cache-key }}
        echo ${{ inputs.lint-cache-key == false }}
      shell: bash
    - uses: actions/cache@v3
      if: ${{ inputs.lint-cache-key != false }}
      with:
        path: |
          .eslintcache
          .stylelintcache
          node_modules/.cache/prettier/.prettier-cache
          tsconfig.build.tsbuildinfo
        key: ${{ runner.os }}-lint-cache-${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-lint-cache-
