name: "Semantic Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run conventional-release
        uses: ./conventional-release
        with:
          create-release: true
